# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url:
date_format: "ordinal"
title: 豆仔gogo
subtitle: "专注后端知识"
description: "有时候阳光很好，有时候阳光很暗，这就是生活。"
keywords: 豆仔gogo
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 2

# ---------------- #
#      Author      #
# ---------------- #
author: 进击de豆子
organization: gopher
organization_url: https://github.com/taoey
github_username: taoey
location: 北京, China
email: taoeyhuang@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 个人随笔
      -
        href: /2021/
        label: 2021

  -
    href: /links/
    label: 友链

  -
    href: /go_learn/
    label: go语言生态

  # -
  #   href: /about/
  #   label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: taoey/taoey.github.io/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie
comments_provider: netease_gentie
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: G-5KYYFB6EFB
baidu: https://hm.baidu.com/hm.js?a1e76086af5c7476151191179c49968a
# 网站备案号
beian: 冀ICP备17029280号-3